-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema materialy
-- -----------------------------------------------------
-- materialy udostepniania materialow

-- -----------------------------------------------------
-- Schema materialy
--
-- materialy udostepniania materialow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `materialy` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `materialy` ;

-- -----------------------------------------------------
-- Table `materialy`.`Uzytkownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Uzytkownik` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Uzytkownik` (
  `idUzytkownik` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NOT NULL COMMENT '',
  `imie` VARCHAR(45) NULL COMMENT '',
  `nazwisko` VARCHAR(45) NULL COMMENT '',
  `haslo` VARCHAR(45) NOT NULL COMMENT '',
  `typ_konta` VARCHAR(10) NOT NULL COMMENT '',
  `nazwa` VARCHAR(45) NULL COMMENT '',
  `skrot` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUzytkownik`)  COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `materialy`.`Przedmiot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Przedmiot` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Przedmiot` (
  `idPrzedmiot` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `nazwa` VARCHAR(45) NOT NULL COMMENT '',
  `aktualizacja` DATETIME NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  `uzytkownik` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPrzedmiot`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materialy`.`Kategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Kategoria` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Kategoria` (
  `idKategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nazwa` VARCHAR(45) NOT NULL COMMENT '',
  `idPrzedmiot` INT NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idKategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materialy`.`Podkategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Podkategoria` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Podkategoria` (
  `idPodkategoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nazwa` VARCHAR(45) NOT NULL COMMENT '',
  `idKategoria` INT NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  INDEX `fk_Podkategoria_Kategoria_idx` (`idKategoria` ASC)  COMMENT '',
  PRIMARY KEY (`idPodkategoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materialy`.`Prowadzacy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Prowadzacy` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Prowadzacy` (
  `idPrzedmiot` INT NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materialy`.`Ogloszenia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Ogloszenia` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Ogloszenia` (
  `idOgloszenia` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tytul` VARCHAR(45) NOT NULL COMMENT '',
  `tresc` VARCHAR(45) NOT NULL COMMENT '',
  `idPrzedmiot` INT NOT NULL COMMENT '',
  `data` DATETIME NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idOgloszenia`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materialy`.`Plik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Plik` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Plik` (
  `idPlik` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nazwa` VARCHAR(45) NOT NULL COMMENT '',
  `data` VARCHAR(45) NOT NULL COMMENT '',
  `idUzytkownik` INT NOT NULL COMMENT '',
  `idPodkategoria` INT NOT NULL COMMENT '',
  `tytul` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idPlik`)  COMMENT '',
  UNIQUE INDEX `idPlik_UNIQUE` (`idPlik` ASC)  COMMENT '')
ENGINE = InnoDB;

INSERT INTO Uzytkownik (`idUzytkownik`, `login`, `imie`, `nazwisko`, `haslo`, `typ_konta`, `nazwa`, `skrot`) VALUES 
(1, 'admin', 'admin', 'admin', '4f491f4950c1d7ca054f9f97e457cf79', 'admin', '', '');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
