-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema materialy
-- -----------------------------------------------------
-- materialy udostepniania materialow

-- -----------------------------------------------------
-- Schema materialy
--
-- materialy udostepniania materialow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `materialy` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `materialy` ;

-- -----------------------------------------------------
-- Table `materialy`.`Uzytkownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materialy`.`Uzytkownik` ;

CREATE TABLE IF NOT EXISTS `materialy`.`Uzytkownik` (
  `idUzytkownik` INT(10) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NOT NULL COMMENT '',
  `imie` VARCHAR(45) NULL COMMENT '',
  `nazwisko` VARCHAR(45) NULL COMMENT '',
  `haslo` VARCHAR(45) NOT NULL COMMENT '',
  `typ_konta` VARCHAR(10) NOT NULL COMMENT '',
  `nazwa` VARCHAR(45) NULL COMMENT '',
  `skrot` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idUzytkownik`)  COMMENT '')
ENGINE = InnoDB;

INSERT INTO Uzytkownik (`idUzytkownik`, `login`, `imie`, `nazwisko`, `haslo`, `typ_konta`, `nazwa`, `skrot`) VALUES 
(1, 'admin', 'admin', 'admin', '4f491f4950c1d7ca054f9f97e457cf79', 'admin', '', '');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
